---
  - name: Remove rescue images
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop: "{{ query('fileglob', '/boot/*rescue*') | sort }}"

  - name: Uninstall packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: absent
    with_items:
      - motd-news-config
      - command-not-found
      - update-notifier-common

  - name: Cleaning up
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /root/.cache
      - /root/.lesshst
      - /root/.rnd
      - /root/anaconda-ks.cfg
      - /root/setup.retry
      - /var/tmp/abrt
