---
- name: Install helpful packages
  ansible.builtin.package: name={{ item }} state=present
  with_items:
    - logrotate

  ignore_errors: true

- name: Configure logrotate.conf
  ansible.builtin.lineinfile:
    dest: /etc/logrotate.conf
    create: true
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: "^compress", line: "compress"}
    - {regexp: "^rotate.*", line: "rotate 14"}
    - {regexp: "^daily", line: "daily"}
    - {regexp: "^weekly.*", line: ""}
    - {regexp: "^dateext.*", line: ""}

- name: Limit Journal file size
  community.general.ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: SystemMaxUse
    value: 200M
